-- SUB QUERIES
-- Sub Query where the inner query depends on outer query
-- using 
-- WHERE  CLAUSE
-- FROM CLAUSE 
-- CO-RELATED QUERY (Both Query Depends on inne as well as outer its like a loop)
-- SINGLE VALUE